version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: '00:00'
      timezone: America/Sao_Paulo
    pull-request-branch-name:
      separator: '-'
    rebase-strategy: disabled
    groups:
      minor-updates:
        patterns:
          - '*'
        update-types: [minor]
      patch-updates:
        patterns:
          - '*'
        update-types: [patch]
      major-updates:
        patterns:
          - '*'
        update-types: [major]
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
