name: Setup
description: Setup Nodejs, pnpm and install dependencies

inputs:
  node-version:
    description: Nodejs version to install
    required: true
    default: 22.x

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile --prefer-offline

    - name: Cache test results
      uses: actions/cache@v4
      with:
        path: coverage/
        key: ${{ runner.os }}-coverage-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-coverage-
