coverage:
  precision: 2
  round: down
  range: '80...100'
  status:
    project:
      default:
        target: 80%
        threshold: 5%
    patch:
      default:
        target: 80%
        threshold: 5%

comment:
  layout: 'reach, diff, flags, files'
  behavior: default
  require_changes: false

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

ignore:
  - 'test/'
  - '**/*.test.ts'
  - '**/*.spec.ts'
  - '**/*.test.js'
  - '**/*.spec.js'
  - '**/*.test.vue'
  - '**/*.spec.vue'
  - 'coverage/'
  - '.nuxt/'
  - '.output/'
  - 'dist/'
  - 'build/'
  - 'node_modules/'
  - '*.config.*'
  - '*.d.ts'
